Задание 6. Добавить функциональность регистрации пользователя
gpb-it-factory/elenberger-middle-service pull request #4
Opened 2024-06-06 16:08 UTC by LohmatiyShmel

Сделал прием id и его передачу в back. Перед регистрацией проверяет зарегистрирован ли пользователь. Тесты ПОКА не писал, хочу понять двигаюсь ли в правильном направлении. Насколько это адекватно с точки зрения архитектуры и соответствует заданию.

2024-06-13 06:04 UTC, DirtyRamirez requested changes
пара замечаний

2024-06-13 06:04 UTC, DirtyRamirez commented on src/main/java/com/gpbitfactory/middle/service/MiddleService.java
> +        if (response.getStatusCode().is2xxSuccessful()) {
можно просто `return response.getStatusCode().is2xxSuccessful()`

2024-06-13 06:04 UTC, DirtyRamirez commented on src/main/java/com/gpbitfactory/middle/controller/MiddleController.java
> +        } else {
можно без else

2024-06-15 15:35 UTC, LohmatiyShmel commented
Поменял реализации в соответствии с комментариями. Сделал тесты

2024-06-17 12:20 UTC, DirtyRamirez approved these changes

2024-06-17 12:38 UTC, merged