Задание 7. Добавить функциональность создания счёта
gpb-it-factory/elenberger-middle-service pull request #6
Opened 2024-06-19 12:59 UTC by LohmatiyShmel

2024-06-25 18:24 UTC, vaganov-vadim requested changes
Привет! Очень круто! Добавил пару комментов, где можно что-то улучшить.

2024-06-25 18:24 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/middle/service/AccountService.java
> +    private final RestTemplate restTemplate;
Как рекомендация Spring - лучше использовать RestClient.

2024-06-25 18:24 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/middle/service/AccountService.java
> +    private void postToBack(Long id) {
Вкусовщина, но имхо можно не выносить в отдельную функцию, и так в целом понятно, что делаем.

2024-06-25 18:24 UTC, vaganov-vadim commented on src/test/java/com/gpbitfactory/middle/serviceTest/AccountServiceTest.java
> +        Assertions.assertEquals(204, accountService.createAccount(requestDTO.userID()));
Чуть читаемее будет, если написать по паттерну Arrange Act Assert. То бишь createAccount вынести на отдельную строку и каждый этап разделить пустыми строками.

2024-06-26 13:13 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/middle/service/AccountService.java
> +    private final RestTemplate restTemplate;
Да, почитал что такое. Как-то не заметил что RestTemplate помечен устаревшим. Переписал на RestClient

2024-06-26 13:14 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/middle/service/AccountService.java
> +    private void postToBack(Long id) {
Надо избавляться от дурной привычке мне. Нашел такой же однострочник. Его тоже поправил

2024-06-26 13:16 UTC, LohmatiyShmel commented on src/test/java/com/gpbitfactory/middle/serviceTest/AccountServiceTest.java
> +        Assertions.assertEquals(204, accountService.createAccount(requestDTO.userID()));
Сейчас переписал на RestClient и понял в чем была моя проблема подходов к тестам. С черным ящиком можешь как угодно менять реализацию, если результат ожидаемый, ничего перекапывать не надо. Прям удивлен

2024-06-26 13:16 UTC, LohmatiyShmel commented on src/test/java/com/gpbitfactory/middle/serviceTest/AccountServiceTest.java
> +        Assertions.assertEquals(204, accountService.createAccount(requestDTO.userID()));
Отформатирую чтобы было читабельнее

2024-06-26 16:10 UTC, vaganov-vadim approved these changes
Круто, аппрув!

2024-06-26 16:34 UTC, merged